version: "3.3"

services:
  localstack:
    container_name: localstack-sam-sample
    image: localstack/localstack
    ports:
      - 8080:8080
      - 4569:4569 # DynamoDB
      - 4576:4576 # SQS
    environment:
      - SERVICES=dynamodb,sqs
    networks:
      - nw-sam-sample

networks:
  nw-sam-sample:
    external: true
